## Comment Policy

The following rules are a slightly modified version of what is suggested by Disqus.

Please, try your damnedest to abide by them.  Be polite, be professional.  Thank you!

## The Rules:

### Keep it civil (aka "Don’t be a jerk!")

We’re going to get into the thick of a lot of heated discussions and that’s okay. These discussions often entail topics that we all personally care a lot about and will passionately defend. But in order for discussions to thrive here, we need to remember to criticize ideas, not people. 
 
So, remember to avoid:

    - name-calling
    - ad hominem attacks
    - responding to a post’s tone instead of its actual content.
    - knee-jerk contradiction
    - comments that we find to be hateful, inflammatory, or harassing may be removed. If you don’t have something nice to say about another user, don't say it. 
    - treat others the way you’d like to be treated.

Always strive to add value to every interaction and discussion in which you participate.

If you are not sure your post adds to the conversation, think over what you want to say and try again later.

### Keep it tidy

Help make my life easier by taking a moment to ensure that what you’re about to post is in the right place. That means:

    - don’t post off-topic comments or discussions
    - don’t cross-post the same thing multiple times

If you see something, say something: moderating comments can be difficult, but it's something we can do together.  So, if you see an issue, contact me if possible or flag any comments for review. If you believe someone has violated this site's Comment Policy, report it to Disqus by flagging the user's profile.

Some Additional Clarification(s):

### Stay On-topic

Be sure your comment stays on topic and matches the general theme of the blog post.

### No Self-promotion

A discussion or comment that contains only a link to your blog, a product, or your article on another site will almost always be removed.

### Choose Your (Curse) Words Wisely

Comments that contain profanity are automatically held for moderator review before being posted. Depending on the context of the comment, it may be removed. Profanity used to insult, antagonize, or inflame will always be removed.

### Don’t Be a Jerk

Personal attacks and harassment will not be tolerated. Sexist, racist, misogynist, homophobic, and broad, offensive generalizations about groups of people are simply not allowed. Comments or discussions written intentionally to provoke will also be removed.

### Don’t Copy and Paste

If you didn’t write it, or haven’t properly cited the article you’re quoting, don’t post it.

### English Only

We currently only support English-only discussions on Disqus channels. Non-English comments and discussions will be removed.  If you don't speak English, please try [Google Translate](https://translate.google.com/).